USE JPR;



 CREATE TABLE studentdetail (Dateofjoin	VARCHAR(300),Rollno	VARCHAR(150),Title	VARCHAR(100),STUDENT 	VARCHAR(300),Initial	VARCHAR(50),DayScholarorHostel	VARCHAR(50),
     DEPARTMENT	VARCHAR(250),
     DOB	VARCHAR(50),
     RELIGION	VARCHAR(50),
     BG	VARCHAR(50),
     StudentMobile 	VARCHAR(150),
     StudentEmail	VARCHAR(300),
     AadharNo	VARCHAR(150),
     Identification	VARCHAR(200),
     PlaceofBrith 	VARCHAR(200),
     ExtraActivities	VARCHAR(200),
     tenthpercentage	VARCHAR(100),
     tenthMarks	VARCHAR(100),
     School	VARCHAR(300),
     Tenthpassed	VARCHAR(100),
     twelthpercent	varchar(100),
     twelthmarks	varchar(100),
     twelthschool	varchar(300),
     twelthPassed	varchar(100),
     Physics	varchar(300),
     Chemistry	varchar(300),
     Maths	varchar(100),
     Cutoff	varchar(100),
     Medium	varchar(100),
     Diploma	varchar(100),
     diplonacollege	varchar(300),
     Diplomayear	varchar(50),
     DSorH	varchar(50),
     BusNumber	varchar(50),
     BoardingPoint	varchar(300),
     Community	varchar(100),
     Caste	varchar(100),
     MotherTongue	varchar(100),
     Gender	varchar(50),
     VegorNonveg	varchar(50),
     PhysicallyHandicapped	varchar(300),
     PermanentAddressLine1	varchar(300),
     PermanentAddressLine2	varchar(300),
     PermanentAddressLine3	varchar(300),
     CommunicationAddressLine1	varchar(300),
     CommunicationAddressLine2	varchar(300),
     CommunicationAddressLine3	varchar(300),
     FatherName	varchar(300),
     FatherQualification	varchar(300),
     FatherOccupation	varchar(300),
     FatherMobile	varchar(100),
     FatherEmail 	varchar(100),
     FatherIncome	varchar(100),
     MotherName	varchar(300),
     MotherQualification	varchar(300),
     MotherOccupation	varchar(300),
     MotherMobile	varchar(100),
     MotherEmail	varchar(100),
     MotherIncome	varchar(100),
     GuardianName	varchar(300),
     GuardianMobile	varchar(100),
     GuardianAddress	varchar(100),
     photo BLOB
        );
 